services:
  solr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solr_nginx_lua_proxy
    ports:
      - "8988:8983"
    volumes:
      - solr_proxy_data:/var/solr
      - ./solr_config:/opt/solr/server/solr/configsets/_default/conf
    environment:
      SOLR_JAVA_MEM: "-Xms512m -Xmx512m"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8988/solr/"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - moodle_network

volumes:
  solr_proxy_data:
networks:
  moodle_network:
    external: true
    name: ${MOODLE_NETWORK:-moodle-docker_default}
