services:
  solr:
    build:
      context: .
      dockerfile: Dockerfile.solr
    container_name: solr_nginx_lua_proxy
    ports:
      - "8988:8983"
    volumes:
      - solr_proxy_data:/var/solr
      - ./solr_config:/opt/solr/server/solr/configsets/_default/conf
    environment:
      SOLR_JAVA_MEM: "-Xms512m -Xmx512m"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8988/solr/"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - moodle_network
  nginx-proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx_lua_proxy
    ports:
      - "8983:80"  # Nginx proxy on the port clients expect
    environment:
      - SOLR_HOST=solr
      - SOLR_PORT=8983
    depends_on:
      - solr
    networks:
      - moodle_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

volumes:
  solr_proxy_data:
networks:
  moodle_network:
    external: true
    name: ${MOODLE_NETWORK:-moodle-docker_default}
